define([], function () {
  return {
    SettingsGroupName: "Innstillinger",
    ViewsGroupName: "Visninger",
    LookAndFeelGroupName: "Utseende og funksjonalitet",
    PersistedPhasePropertyBagKey: "persisted_phase",
    PhaseFieldFieldLabel: "Felt",
    AutomaticReloadFieldLabel: "Automatisk oppdatering",
    ReloadTimeoutFieldLabel: "Forsinkelse (s)",
    FontSizeFieldLabel: "Skriftstørrelse",
    GutterFieldLabel: "Avstand mellom fasene",
    UpdateViewsDocumentsFieldLabel: "Opppdater Prosjektdokumenter",
    UpdateViewsTasksFieldLabel: "Oppdater Oppgaver",
    UpdateViewsRisksFieldLabel: "Oppdater Usikkerhet",
    ConfirmPhaseChangeFieldLabel: "Bekreft faseenendring",
    PhaseSubTextPropertyFieldLabel: "Egenskap for undertekst",
    ConfirmPhaseDialogTitle: "Endre fase",
    ConfirmPhaseDialogSubText: "Endring av fasen til {0} vil endre dette for alle, vil du fortsette?",
    PhaseChangedMessage: "Prosjektet er nå i fase {0}.",
    PageReloadMessage: "Oppdater siden for å få oppdaterte listevisninger.",
    WebPartNotConfiguredMessage: "Webdelen er ikke konfigurert riktig. Du må angi webpartegenskaper riktig.",
    DocumentsListName: "Prosjektdokumenter",
    RiskRegisterListName: "Usikkerhet",
    TasksListName: "Oppgaver",
    Yes: "Ja",
    No: "Nei",
    CheckPointsMarkedAsText: "sjekkpunkter markert som",
    GoToPhaseChecklist: "Gå til fasesjekklisten"
  }
});